/**
 * AUTO-GENERATED FILE — DO NOT EDIT DIRECTLY
 * Generated by scripts/build_gifs.js
 */

export const EXERCISE_GIFS: Record<string, any> = {
  '05Cf2v8': require('../../Exercises/exercisedb_v1_sample/gifs_360x360/05Cf2v8.gif'),
  '2ORFMoR': require('../../Exercises/exercisedb_v1_sample/gifs_360x360/2ORFMoR.gif'),
  '2Qh2J1e': require('../../Exercises/exercisedb_v1_sample/gifs_360x360/2Qh2J1e.gif'),
  '3eGE2JC': require('../../Exercises/exercisedb_v1_sample/gifs_360x360/3eGE2JC.gif'),
  '3tAXPQ6': require('../../Exercises/exercisedb_v1_sample/gifs_360x360/3tAXPQ6.gif'),
  '3TZduzM': require('../../Exercises/exercisedb_v1_sample/gifs_360x360/3TZduzM.gif'),
  '3XFdb1Z': require('../../Exercises/exercisedb_v1_sample/gifs_360x360/3XFdb1Z.gif'),
  '4dF3maG': require('../../Exercises/exercisedb_v1_sample/gifs_360x360/4dF3maG.gif'),
  '4dUn2iv': require('../../Exercises/exercisedb_v1_sample/gifs_360x360/4dUn2iv.gif'),
  '5bpPTHv': require('../../Exercises/exercisedb_v1_sample/gifs_360x360/5bpPTHv.gif'),
  '5uFK1xr': require('../../Exercises/exercisedb_v1_sample/gifs_360x360/5uFK1xr.gif'),
  '5v7KYld': require('../../Exercises/exercisedb_v1_sample/gifs_360x360/5v7KYld.gif'),
  '6bOA1Oi': require('../../Exercises/exercisedb_v1_sample/gifs_360x360/6bOA1Oi.gif'),
  '6cKQC5E': require('../../Exercises/exercisedb_v1_sample/gifs_360x360/6cKQC5E.gif'),
  '6HiHHe0': require('../../Exercises/exercisedb_v1_sample/gifs_360x360/6HiHHe0.gif'),
  '6kSxYnw': require('../../Exercises/exercisedb_v1_sample/gifs_360x360/6kSxYnw.gif'),
  '6MfS53i': require('../../Exercises/exercisedb_v1_sample/gifs_360x360/6MfS53i.gif'),
  '6sMAmNv': require('../../Exercises/exercisedb_v1_sample/gifs_360x360/6sMAmNv.gif'),
  '6sYyrRX': require('../../Exercises/exercisedb_v1_sample/gifs_360x360/6sYyrRX.gif'),
  '7F1DVzn': require('../../Exercises/exercisedb_v1_sample/gifs_360x360/7F1DVzn.gif'),
  '7I6LNUG': require('../../Exercises/exercisedb_v1_sample/gifs_360x360/7I6LNUG.gif'),
  '7inpWch': require('../../Exercises/exercisedb_v1_sample/gifs_360x360/7inpWch.gif'),
  '7saC5zz': require('../../Exercises/exercisedb_v1_sample/gifs_360x360/7saC5zz.gif'),
  '7zdxRTl': require('../../Exercises/exercisedb_v1_sample/gifs_360x360/7zdxRTl.gif'),
  '8eqjhOl': require('../../Exercises/exercisedb_v1_sample/gifs_360x360/8eqjhOl.gif'),
  '8K0w2yA': require('../../Exercises/exercisedb_v1_sample/gifs_360x360/8K0w2yA.gif'),
  '8oYqOt9': require('../../Exercises/exercisedb_v1_sample/gifs_360x360/8oYqOt9.gif'),
  '8ozhUIZ': require('../../Exercises/exercisedb_v1_sample/gifs_360x360/8ozhUIZ.gif'),
  '8urJS9b': require('../../Exercises/exercisedb_v1_sample/gifs_360x360/8urJS9b.gif'),
  '8xUv4J7': require('../../Exercises/exercisedb_v1_sample/gifs_360x360/8xUv4J7.gif'),
};

export function getExerciseGif(id: string): any | null {
  return EXERCISE_GIFS[id] ?? null;
}
