const fs = require('fs');
const path = require('path');

const GIF_DIR = path.join(__dirname, '../Exercises/exercisedb_v1_sample/gifs_360x360');
const OUTPUT_FILE = path.join(__dirname, '../src/exercise/exerciseGifMap.ts');

function buildGifMap() {
  if (!fs.existsSync(GIF_DIR)) {
    console.error(`Directory not found: ${GIF_DIR}`);
    process.exit(1);
  }

  const files = fs.readdirSync(GIF_DIR).filter(f => f.endsWith('.gif'));
  
  let out = `/**\n * AUTO-GENERATED FILE — DO NOT EDIT DIRECTLY\n * Generated by scripts/build_gifs.js\n */\n\n`;
  out += `export const EXERCISE_GIFS: Record<string, any> = {\n`;
  
  files.forEach(file => {
    const id = file.replace('.gif', '');
    out += `  '${id}': require('../../Exercises/exercisedb_v1_sample/gifs_360x360/${file}'),\n`;
  });
  
  out += `};\n\n`;
  out += `export function getExerciseGif(id: string): any | null {\n`;
  out += `  return EXERCISE_GIFS[id] ?? null;\n`;
  out += `}\n`;

  fs.writeFileSync(OUTPUT_FILE, out);
  console.log(`Generated exerciseGifMap.ts with ${files.length} mappings.`);
}

buildGifMap();
