/**
 * NutritionService — Loads and searches the food datasets.
 * 
 * Datasets:
 * - Indian food: Nutrition/Indian_Food_Nutrition_Processed.csv
 * - All foods: Nutrition/FINAL FOOD DATASET/FOOD-DATA-GROUP1-5.csv
 * 
 * Both are bundled via raw-loader/require as text files.
 * In Expo, we read them as static assets via require() or expo-asset.
 */
import { FoodItem, NutritionSuggestion, MealPlanItem, MacroSummary } from './nutritionTypes';
import { parseCSV, parseNum } from './csvParser';

// ─── Dataset Loading ─────────────────────────────────────────────────────────

// We load CSV text via require — Expo/Metro can bundle text files with
// an appropriate transformer, but to avoid configuration changes, we embed
// the data as pre-parsed JSON arrays generated by a build script.
// Fallback: load from a bundled JSON version if CSVs aren't directly readable.

let _indianFoods: FoodItem[] | null = null;
let _globalFoods: FoodItem[] | null = null;
let _allFoods: FoodItem[] | null = null;

/**
 * Load and parse the Indian food dataset.
 * CSV columns: Dish Name, Calories (kcal), Carbohydrates (g), Protein (g),
 *              Fats (g), Free Sugar (g), Fibre (g), Sodium (mg), Calcium (mg),
 *              Iron (mg), Vitamin C (mg), Folate
 */
function loadIndianFoods(): FoodItem[] {
  if (_indianFoods) return _indianFoods;

  try {
    // Try loading from pre-built JSON (generated by build script)
    const data = require('../../Nutrition/indian_foods_data.json');
    _indianFoods = data;
    return _indianFoods!;
  } catch {
    // Fallback: return a curated subset of common Indian foods
    _indianFoods = INDIAN_FOOD_FALLBACK;
    return _indianFoods;
  }
}

/**
 * Load and parse the global food dataset.
 */
function loadGlobalFoods(): FoodItem[] {
  if (_globalFoods) return _globalFoods;

  try {
    const data = require('../../Nutrition/global_foods_data.json');
    _globalFoods = data;
    return _globalFoods!;
  } catch {
    _globalFoods = GLOBAL_FOOD_FALLBACK;
    return _globalFoods;
  }
}

/**
 * Get all foods (combined Indian + global).
 */
function getAllFoods(): FoodItem[] {
  if (_allFoods) return _allFoods;
  _allFoods = [...loadIndianFoods(), ...loadGlobalFoods()];
  return _allFoods;
}

// ─── Search ──────────────────────────────────────────────────────────────────

/**
 * Fuzzy search across all food datasets.
 * Returns results ranked by match quality.
 */
export function searchFood(query: string, limit: number = 20): FoodItem[] {
  if (!query || query.trim().length < 2) return [];

  const q = query.toLowerCase().trim();
  const words = q.split(/\s+/);
  const all = getAllFoods();

  const scored = all
    .map(food => {
      const name = food.name.toLowerCase();
      let score = 0;

      // Exact match
      if (name === q) score += 100;
      // Starts with query
      else if (name.startsWith(q)) score += 80;
      // Contains full query
      else if (name.includes(q)) score += 60;
      // All words present
      else if (words.every(w => name.includes(w))) score += 40;
      // Any word present
      else if (words.some(w => name.includes(w) && w.length > 2)) score += 20;

      // Boost Indian foods slightly for Indian queries
      if (food.source === 'indian' && isLikelyIndianQuery(q)) score += 10;

      return { food, score };
    })
    .filter(({ score }) => score > 0)
    .sort((a, b) => b.score - a.score)
    .slice(0, limit)
    .map(({ food }) => food);

  // If no results, use AI estimation
  if (scored.length === 0) {
    const estimated = estimateByAI(query);
    if (estimated) return [estimated];
  }

  return scored;
}

function isLikelyIndianQuery(query: string): boolean {
  const indianKeywords = ['curry', 'dal', 'roti', 'rice', 'biryani', 'sabzi', 'paneer',
    'dosa', 'idli', 'sambar', 'chai', 'lassi', 'raita', 'naan', 'paratha',
    'aloo', 'gobi', 'masala', 'chana', 'rajma', 'kadhi', 'upma', 'poha'];
  return indianKeywords.some(kw => query.includes(kw));
}

/**
 * Get nutritional info for a specific food item, scaled to a serving size.
 */
export function getNutrition(foodItem: FoodItem, servingG: number): FoodItem {
  const ratio = servingG / (foodItem.servingG || 100);
  return {
    ...foodItem,
    servingG,
    kcal: Math.round(foodItem.kcal * ratio),
    protein: Math.round(foodItem.protein * ratio * 10) / 10,
    carbs: Math.round(foodItem.carbs * ratio * 10) / 10,
    fat: Math.round(foodItem.fat * ratio * 10) / 10,
    fiber: foodItem.fiber ? Math.round(foodItem.fiber * ratio * 10) / 10 : 0,
    sugar: foodItem.sugar ? Math.round(foodItem.sugar * ratio * 10) / 10 : 0,
    sodium: foodItem.sodium ? Math.round(foodItem.sodium * ratio) : 0,
  };
}

/**
 * AI estimation fallback for unknown foods.
 * Uses a knowledge base of common food macros per 100g.
 */
export function estimateByAI(query: string): FoodItem | null {
  const q = query.toLowerCase();

  const estimates: Record<string, Omit<FoodItem, 'id' | 'name' | 'source' | 'isEstimated'>> = {
    // Proteins
    'chicken': { servingG: 100, kcal: 165, protein: 31, carbs: 0, fat: 3.6, fiber: 0 },
    'egg': { servingG: 50, kcal: 78, protein: 6, carbs: 0.6, fat: 5.3, fiber: 0 },
    'fish': { servingG: 100, kcal: 180, protein: 26, carbs: 0, fat: 8, fiber: 0 },
    'beef': { servingG: 100, kcal: 250, protein: 26, carbs: 0, fat: 15, fiber: 0 },
    'tofu': { servingG: 100, kcal: 76, protein: 8, carbs: 2, fat: 4, fiber: 0.3 },
    // Carbs
    'rice': { servingG: 150, kcal: 200, protein: 4, carbs: 44, fat: 0.5, fiber: 0.6 },
    'bread': { servingG: 30, kcal: 80, protein: 3, carbs: 15, fat: 1, fiber: 0.6 },
    'pasta': { servingG: 80, kcal: 280, protein: 10, carbs: 55, fat: 1.5, fiber: 2 },
    'oats': { servingG: 40, kcal: 150, protein: 5, carbs: 27, fat: 3, fiber: 4 },
    'banana': { servingG: 120, kcal: 105, protein: 1.3, carbs: 27, fat: 0.4, fiber: 3 },
    'apple': { servingG: 182, kcal: 95, protein: 0.5, carbs: 25, fat: 0.3, fiber: 4 },
    // Indian
    'idli': { servingG: 100, kcal: 58, protein: 2, carbs: 12, fat: 0.1, fiber: 0.4 },
    'dosa': { servingG: 100, kcal: 168, protein: 4, carbs: 33, fat: 2, fiber: 0.8 },
    'roti': { servingG: 40, kcal: 100, protein: 3, carbs: 20, fat: 1, fiber: 2 },
    'dal': { servingG: 150, kcal: 130, protein: 9, carbs: 22, fat: 1, fiber: 5 },
    'biryani': { servingG: 250, kcal: 450, protein: 20, carbs: 60, fat: 15, fiber: 2 },
    'paneer': { servingG: 100, kcal: 265, protein: 18, carbs: 2, fat: 20, fiber: 0 },
    'samosa': { servingG: 60, kcal: 170, protein: 3, carbs: 18, fat: 9, fiber: 1 },
    // Dairy
    'milk': { servingG: 240, kcal: 150, protein: 8, carbs: 12, fat: 8, fiber: 0 },
    'yogurt': { servingG: 170, kcal: 100, protein: 17, carbs: 6, fat: 0.7, fiber: 0 },
    'cheese': { servingG: 28, kcal: 110, protein: 7, carbs: 0.4, fat: 9, fiber: 0 },
    // Extras
    'coffee': { servingG: 240, kcal: 5, protein: 0.3, carbs: 0.7, fat: 0, fiber: 0 },
    'tea': { servingG: 240, kcal: 16, protein: 0.4, carbs: 2.6, fat: 0.5, fiber: 0 },
    'water': { servingG: 250, kcal: 0, protein: 0, carbs: 0, fat: 0, fiber: 0 },
  };

  for (const [keyword, data] of Object.entries(estimates)) {
    if (q.includes(keyword)) {
      return {
        id: `ai_${keyword}`,
        name: query.charAt(0).toUpperCase() + query.slice(1),
        source: 'global',
        isEstimated: true,
        ...data,
      };
    }
  }

  // Generic unknown — very rough estimate
  return {
    id: `ai_unknown_${Date.now()}`,
    name: query.charAt(0).toUpperCase() + query.slice(1),
    source: 'global',
    servingG: 100,
    kcal: 200,
    protein: 8,
    carbs: 25,
    fat: 8,
    isEstimated: true,
  };
}

// ─── AI Nutrition Coach ──────────────────────────────────────────────────────

/**
 * Generate AI coaching suggestions based on today's nutrition vs targets.
 */
export function generateNutritionSuggestions(
  totals: MacroSummary,
  targets: MacroSummary,
  timeOfDay: number = new Date().getHours()
): NutritionSuggestion[] {
  const suggestions: NutritionSuggestion[] = [];
  const remaining = {
    kcal: targets.kcal - totals.kcal,
    protein: targets.protein - totals.protein,
    carbs: targets.carbs - totals.carbs,
    fat: targets.fat - totals.fat,
    water: (targets.water || 3000) - totals.water,
  };

  // Protein check
  if (remaining.protein > 40) {
    suggestions.push({
      id: 'protein_low',
      type: 'warning',
      message: `You still need ${Math.round(remaining.protein)}g protein. Add chicken, eggs, or paneer to your next meal.`,
      priority: 10,
    });
  } else if (remaining.protein < -10) {
    suggestions.push({
      id: 'protein_over',
      type: 'tip',
      message: `Protein target exceeded by ${Math.abs(Math.round(remaining.protein))}g. Great job on hitting your protein goal!`,
      priority: 5,
    });
  } else if (remaining.protein <= 20 && remaining.protein > 0) {
    suggestions.push({
      id: 'protein_close',
      type: 'success',
      message: `Almost there! Just ${Math.round(remaining.protein)}g more protein needed today.`,
      priority: 7,
    });
  }

  // Calorie balance
  if (remaining.kcal < -300) {
    suggestions.push({
      id: 'kcal_over',
      type: 'warning',
      message: `Caloric surplus of ${Math.abs(Math.round(remaining.kcal))} kcal. Consider lighter meals for the rest of the day.`,
      priority: 9,
    });
  } else if (remaining.kcal > 500 && timeOfDay >= 18) {
    suggestions.push({
      id: 'kcal_under_evening',
      type: 'warning',
      message: `Caloric deficit detected: ${Math.round(remaining.kcal)} kcal remaining. Eating too little may increase catabolism risk.`,
      priority: 8,
    });
  }

  // Fat check
  if (remaining.fat < -15) {
    suggestions.push({
      id: 'fat_over',
      type: 'tip',
      message: 'Reduce fat intake today. Choose grilled over fried and opt for low-fat proteins.',
      priority: 6,
    });
  }

  // Water check
  if (remaining.water > 1000) {
    suggestions.push({
      id: 'water_low',
      type: 'tip',
      message: `Drink ${Math.round(remaining.water / 1000 * 10) / 10}L more water today. Hydration improves performance and recovery.`,
      priority: 8,
    });
  } else if (remaining.water <= 0) {
    suggestions.push({
      id: 'water_done',
      type: 'success',
      message: 'Daily hydration goal achieved. Hunter vitality maintained.',
      priority: 3,
    });
  }

  // Carb balance
  if (totals.carbs / targets.carbs >= 0.9 && totals.carbs / targets.carbs <= 1.1) {
    suggestions.push({
      id: 'carb_good',
      type: 'success',
      message: 'Good carbohydrate balance. Energy systems optimal for training.',
      priority: 2,
    });
  }

  // Pre-workout nutrition window (11am-2pm if user works out in afternoon)
  if (timeOfDay >= 11 && timeOfDay <= 14 && totals.kcal < 400) {
    suggestions.push({
      id: 'pre_workout',
      type: 'coach',
      message: 'Pre-workout nutrition window: Consume 400-600 kcal with complex carbs 90-120 min before training.',
      priority: 7,
    });
  }

  return suggestions.sort((a, b) => b.priority - a.priority);
}

/**
 * Generate a daily meal plan based on user goals and preferences.
 */
export function generateMealPlan(
  targetKcal: number,
  targetProtein: number,
  targetCarbs: number,
  targetFat: number,
  preferences: {
    vegetarian?: boolean;
    vegan?: boolean;
    includeIndian?: boolean;
  } = {}
): MealPlanItem[] {
  const { vegetarian = false, vegan = false, includeIndian = true } = preferences;

  const distribution = {
    breakfast: 0.25,
    'pre-workout': 0.15,
    lunch: 0.30,
    'post-workout': 0.10,
    dinner: 0.20,
  };

  const proteinFoods = vegan
    ? ['tofu', 'lentils', 'chickpeas', 'tempeh']
    : vegetarian
    ? ['paneer', 'cottage cheese', 'greek yogurt', 'eggs', 'tofu']
    : ['chicken breast', 'eggs', 'fish', 'paneer', 'greek yogurt'];

  const plans: MealPlanItem[] = [
    {
      mealType: 'breakfast',
      foods: [],
      totalKcal: Math.round(targetKcal * distribution.breakfast),
      totalProtein: Math.round(targetProtein * 0.25),
      note: includeIndian
        ? 'Oatmeal / Poha / Upma + Greek Yogurt + Fruits'
        : 'Oatmeal + Whey Protein + Fruits',
    },
    {
      mealType: 'pre-workout',
      foods: [],
      totalKcal: Math.round(targetKcal * distribution['pre-workout']),
      totalProtein: Math.round(targetProtein * 0.10),
      note: 'Banana + Handful of Almonds / Dry fruits',
    },
    {
      mealType: 'lunch',
      foods: [],
      totalKcal: Math.round(targetKcal * distribution.lunch),
      totalProtein: Math.round(targetProtein * 0.30),
      note: includeIndian
        ? `${proteinFoods[0].charAt(0).toUpperCase() + proteinFoods[0].slice(1)} + Rice/Roti + Dal + Salad`
        : `${proteinFoods[0].charAt(0).toUpperCase() + proteinFoods[0].slice(1)} + Rice + Vegetables`,
    },
    {
      mealType: 'post-workout',
      foods: [],
      totalKcal: Math.round(targetKcal * distribution['post-workout']),
      totalProtein: Math.round(targetProtein * 0.15),
      note: 'Protein shake + Banana OR Curd Rice',
    },
    {
      mealType: 'dinner',
      foods: [],
      totalKcal: Math.round(targetKcal * distribution.dinner),
      totalProtein: Math.round(targetProtein * 0.20),
      note: includeIndian
        ? `${proteinFoods[1]?.charAt(0).toUpperCase() + (proteinFoods[1] ?? 'fish').slice(1)} + 2 Rotis + Sabzi + Curd`
        : 'Grilled protein + Quinoa/Sweet potato + Veggies',
    },
  ];

  return plans;
}

// ─── Curated Fallback Datasets ────────────────────────────────────────────────

const INDIAN_FOOD_FALLBACK: FoodItem[] = [
  { id: 'in_001', name: 'Idli', source: 'indian', servingG: 50, kcal: 39, protein: 1.7, carbs: 7.9, fat: 0.2, fiber: 0.4, sodium: 140 },
  { id: 'in_002', name: 'Dosa', source: 'indian', servingG: 80, kcal: 133, protein: 3.5, carbs: 26, fat: 2, fiber: 0.9, sodium: 350 },
  { id: 'in_003', name: 'Upma', source: 'indian', servingG: 150, kcal: 176, protein: 5, carbs: 31, fat: 3, fiber: 2 },
  { id: 'in_004', name: 'Poha', source: 'indian', servingG: 150, kcal: 182, protein: 3.5, carbs: 37, fat: 2, fiber: 1.5 },
  { id: 'in_005', name: 'Roti (Wheat)', source: 'indian', servingG: 40, kcal: 104, protein: 3.5, carbs: 20, fat: 1.5, fiber: 2.3 },
  { id: 'in_006', name: 'Dal Tadka', source: 'indian', servingG: 150, kcal: 132, protein: 8.5, carbs: 22, fat: 1.5, fiber: 5, sodium: 380 },
  { id: 'in_007', name: 'Chicken Curry', source: 'indian', servingG: 200, kcal: 310, protein: 32, carbs: 8, fat: 16, fiber: 1 },
  { id: 'in_008', name: 'Biryani (Chicken)', source: 'indian', servingG: 300, kcal: 500, protein: 28, carbs: 65, fat: 15, fiber: 2 },
  { id: 'in_009', name: 'Paneer Butter Masala', source: 'indian', servingG: 200, kcal: 380, protein: 17, carbs: 14, fat: 28, fiber: 2 },
  { id: 'in_010', name: 'Rajma (Kidney Bean Curry)', source: 'indian', servingG: 200, kcal: 220, protein: 13, carbs: 38, fat: 2, fiber: 8 },
  { id: 'in_011', name: 'Chole (Chickpea Curry)', source: 'indian', servingG: 200, kcal: 270, protein: 14, carbs: 42, fat: 6, fiber: 10 },
  { id: 'in_012', name: 'Sambar', source: 'indian', servingG: 200, kcal: 120, protein: 7, carbs: 18, fat: 2, fiber: 4 },
  { id: 'in_013', name: 'Masala Chai', source: 'indian', servingG: 200, kcal: 65, protein: 2, carbs: 10, fat: 2, sugar: 8 },
  { id: 'in_014', name: 'Lassi (Sweet)', source: 'indian', servingG: 250, kcal: 200, protein: 8, carbs: 30, fat: 5, sugar: 22 },
  { id: 'in_015', name: 'Paneer (Cottage Cheese)', source: 'indian', servingG: 100, kcal: 265, protein: 18, carbs: 2, fat: 20 },
  { id: 'in_016', name: 'White Rice (Cooked)', source: 'indian', servingG: 150, kcal: 200, protein: 4, carbs: 44, fat: 0.5, fiber: 0.6 },
  { id: 'in_017', name: 'Aloo Paratha', source: 'indian', servingG: 120, kcal: 300, protein: 7, carbs: 48, fat: 9, fiber: 3 },
  { id: 'in_018', name: 'Egg (Boiled)', source: 'indian', servingG: 50, kcal: 78, protein: 6.3, carbs: 0.6, fat: 5.3 },
  { id: 'in_019', name: 'Samosa', source: 'indian', servingG: 65, kcal: 180, protein: 3.5, carbs: 20, fat: 9, fiber: 1.5 },
  { id: 'in_020', name: 'Gulab Jamun', source: 'indian', servingG: 50, kcal: 175, protein: 2.5, carbs: 27, fat: 7, sugar: 22 },
  { id: 'in_021', name: 'Khichdi', source: 'indian', servingG: 200, kcal: 210, protein: 8, carbs: 40, fat: 2, fiber: 3 },
  { id: 'in_022', name: 'Rava Idli', source: 'indian', servingG: 50, kcal: 88, protein: 2.3, carbs: 13, fat: 3, fiber: 0.5 },
  { id: 'in_023', name: 'Pongal', source: 'indian', servingG: 150, kcal: 210, protein: 5, carbs: 38, fat: 4, fiber: 1.5 },
  { id: 'in_024', name: 'Egg Biryani', source: 'indian', servingG: 280, kcal: 410, protein: 18, carbs: 60, fat: 12, fiber: 2 },
  { id: 'in_025', name: 'Mutter Paneer', source: 'indian', servingG: 200, kcal: 290, protein: 15, carbs: 20, fat: 17, fiber: 4 },
];

const GLOBAL_FOOD_FALLBACK: FoodItem[] = [
  { id: 'gl_001', name: 'Chicken Breast (Grilled)', source: 'global', servingG: 100, kcal: 165, protein: 31, carbs: 0, fat: 3.6 },
  { id: 'gl_002', name: 'White Rice (Cooked)', source: 'global', servingG: 150, kcal: 200, protein: 4, carbs: 44, fat: 0.5, fiber: 0.6 },
  { id: 'gl_003', name: 'Brown Rice (Cooked)', source: 'global', servingG: 150, kcal: 215, protein: 5, carbs: 45, fat: 2, fiber: 3.5 },
  { id: 'gl_004', name: 'Oatmeal (Cooked)', source: 'global', servingG: 234, kcal: 150, protein: 5, carbs: 27, fat: 2.5, fiber: 4 },
  { id: 'gl_005', name: 'Whole Wheat Bread', source: 'global', servingG: 30, kcal: 80, protein: 4, carbs: 15, fat: 1, fiber: 2 },
  { id: 'gl_006', name: 'Eggs (Scrambled)', source: 'global', servingG: 100, kcal: 150, protein: 10, carbs: 1, fat: 11 },
  { id: 'gl_007', name: 'Milk (Full Fat)', source: 'global', servingG: 240, kcal: 150, protein: 8, carbs: 12, fat: 8, calcium: 276 },
  { id: 'gl_008', name: 'Greek Yogurt (Plain)', source: 'global', servingG: 170, kcal: 100, protein: 17, carbs: 6, fat: 0.7 },
  { id: 'gl_009', name: 'Whey Protein (Scoop)', source: 'global', servingG: 30, kcal: 120, protein: 24, carbs: 3, fat: 1.5 },
  { id: 'gl_010', name: 'Banana', source: 'global', servingG: 118, kcal: 105, protein: 1.3, carbs: 27, fat: 0.4, fiber: 3 },
  { id: 'gl_011', name: 'Apple', source: 'global', servingG: 182, kcal: 95, protein: 0.5, carbs: 25, fat: 0.3, fiber: 4 },
  { id: 'gl_012', name: 'Almonds', source: 'global', servingG: 28, kcal: 160, protein: 6, carbs: 6, fat: 14, fiber: 3.5 },
  { id: 'gl_013', name: 'Peanut Butter', source: 'global', servingG: 32, kcal: 188, protein: 8, carbs: 7, fat: 16, fiber: 1.9 },
  { id: 'gl_014', name: 'Salmon (Grilled)', source: 'global', servingG: 100, kcal: 208, protein: 20, carbs: 0, fat: 13 },
  { id: 'gl_015', name: 'Tuna (Canned in water)', source: 'global', servingG: 100, kcal: 110, protein: 25, carbs: 0, fat: 1 },
  { id: 'gl_016', name: 'Broccoli (Cooked)', source: 'global', servingG: 91, kcal: 30, protein: 2.5, carbs: 6, fat: 0.3, fiber: 2.6 },
  { id: 'gl_017', name: 'Sweet Potato (Baked)', source: 'global', servingG: 130, kcal: 115, protein: 2, carbs: 27, fat: 0.1, fiber: 3.8 },
  { id: 'gl_018', name: 'Quinoa (Cooked)', source: 'global', servingG: 185, kcal: 220, protein: 8, carbs: 39, fat: 3.5, fiber: 5 },
  { id: 'gl_019', name: 'Cottage Cheese', source: 'global', servingG: 100, kcal: 100, protein: 11, carbs: 3, fat: 4.5 },
  { id: 'gl_020', name: 'Beef (Lean Ground)', source: 'global', servingG: 100, kcal: 218, protein: 26, carbs: 0, fat: 12 },
  { id: 'gl_021', name: 'Pasta (Cooked)', source: 'global', servingG: 140, kcal: 220, protein: 8, carbs: 43, fat: 1.3, fiber: 2.5 },
  { id: 'gl_022', name: 'Orange Juice', source: 'global', servingG: 240, kcal: 112, protein: 1.7, carbs: 26, fat: 0.5, vitaminC: 124 },
  { id: 'gl_023', name: 'Black Coffee', source: 'global', servingG: 240, kcal: 5, protein: 0.3, carbs: 0.7, fat: 0 },
  { id: 'gl_024', name: 'Avocado', source: 'global', servingG: 100, kcal: 160, protein: 2, carbs: 9, fat: 15, fiber: 7 },
  { id: 'gl_025', name: 'Lentils (Cooked)', source: 'global', servingG: 198, kcal: 230, protein: 18, carbs: 40, fat: 0.8, fiber: 16 },
];
